Importam/config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'google/import'
  get 'google/help'
  get 'static_pages/help'
  get 'static_pages/google'
  get 'google/authenticate'
  get 'hikes/index'
  get 'google/oauth2callback'
  #post 'google/oauth2callback'

  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'users/index'

end

Importam/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Importam/app/models/books.rb
class Books

  def initialize()
  end

  def get_books
    response = RestClient::Request.execute(
      method: :get,
      url: 'https://api.nytimes.com/svc/books/v3/lists/combined-print-and-e-book-fiction.json',
      headers: {api_key: '06be14f611ba4faf8063012e5a66c6f4'}
    )

Importam/app/models/user.rb
class User < ApplicationRecord
end

Importam/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def google
    render html: "Button & Function Construction in Progress."
  end
end

Importam/app/controllers/google_controller.rb
class GoogleController < ApplicationController

  def import
    #@@num = Number.new(params[:product][:price])
    #@num1 = @@num.retrn
  end

  def help
    #@num2 = @@num.retrn
  end

  def oauth2callback
    response = HTTParty.post('https://accounts.google.com/o/oauth2/token',  body: { client_id: ENV["GOOGLEID"], client_secret: ENV["GOOGLESECRET"], code: params['code'], grant_type: 'authorization_code', redirect_uri: 'http://localhost:3000/google/oauth2callback', scope: params['scope'] }, headers: { 'Accept' => 'application/json' } )
    access_token = response["access_token"]
    @num2 = @@num
    @response = Contacts.new(@num2, access_token).contactsList
    return @response
  end

  def authenticate
    @@num = params[:product][:price]
    redirect_to "https://accounts.google.com/o/oauth2/auth?client_id=#{ENV["GOOGLEID"]}&response_type=code&redirect_uri=http://localhost:3000/google/oauth2callback&scope=https://www.googleapis.com/auth/contacts"
  end
end

Importam/app/controllers/hikes_controller.rb
load '/home/nick/Documents/betterJourney/Importam/app/services/find_humidity.rb'
class HikesController < ApplicationController
  def index
    weather_object = Weather.new("97210")
    @humidity = weather_object.get_humidity()
    return @humidity
  end
end

Importam/app/controllers/person_controller.rb
class PersonController < ApplicationController
  def new
    @person = Person.new
  end
end

Importam/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def google
  end

  def help
  end
end

Importam/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

Importam/app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
  base_title = "Importa"
  if page_title.empty?
    base_title
  else
    "#{base_title} | #{page_title}"
  end
 end
end

Importam/app/helpers/google_helper.rb
module GoogleHelper
end

Importam/app/helpers/ppl_api_call.rb
require 'google/apis/people_v1'
require 'google/api_client/client_secrets'

client_secrets = Google::APIClient::ClientSecrets.load
auth_client = client_secrets.to_authorization
auth_client.update!(
  :scope => 'https://www.googleapis.com/auth/drive.metadata.readonly',
  :redirect_uri => 'http://www.example.com/oauth2callback',
  :additional_parameters => {
    "access_type" => "offline",         # offline access
    "include_granted_scopes" => "true"  # incremental auth
  }

Importam/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

Importam/app/helpers/users_helper.rb
module UsersHelper
end

Importam/app/views/google/authenticated.html.erb
<h1>Thanks, you are authenticated!</h1>
<p>
  Please click <%= link_to "HERE", google_import_path %>
  to import your contacts
</p>

Importam/app/views/google/help.html.erb
<h1>Using Importa:</h1>
   <h2>
     To import you Google Contacts:
   </h2>
   <h2>
     + Please specify the number of contacts you would
       like to display by entering a number in the Page Size field.
   </h2>
   <h2>
     + Then simply press the blue Import button
   </h2>
   <h2>
     + This will prompt you to verify yourself with your google account and you
       will be redirected back to our site where
   </h2>
   <h2>
       <%= link_to "Home", '/', class: "btn btn-lg btn-primary" %>

Importam/app/views/google/import.html.erb
<h1>Import Your Google Contacts Here</h1>
<h2>
  Here is the number you entered:
   <%=# @num1 %>
</h2>

Importam/app/views/google/oauth2callback.html.erb
<h1>Your Contacts</h1>

  <h2>
    <%for i in @response['connections']%>
      <h2>
        <%=i['names'][0]['displayName']%>:
            <%=i['emailAddresses'][0]['value']%>
      </h2>

    <%end%>
  </h2>

Importam/app/views/hikes/index.html.erb
<h1>Here is the humidity you requested!</h1>
<p>
  Humidity Today: <%= @humidity %>
</p>

Importam/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Log in", '#' %></li>
            <li><%= link_to "Sign Up!",   '#' %></li>
            <li><%= link_to "Help", google_help_path %></li>
          </ul>
        </nav>
      </div>
    </header>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

Importam/app/views/person/new.html.erb
<h1>Person Test</h1>
<h2>
  <%= form_for @person.update, url: {action: "create"} do |person_form| %>
  <%= person_form.text_field :name %>
  <%= fields_for @person.update.contact_detail do |contact_detail_form| %>
    <%= contact_detail_form.text_field :phone_number %>
  <% end %>
<% end %>
</h2>

Importam/app/views/static_pages/google.html.erb
<h1></h1>
  <h2>
    Import your Contacts here
  </h2>
  <%= link_to "Import!", '#', class: "btn btn-lg btn-primary" %>

Importam/app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

Importam/app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to the Importa</h1>

  <h2>
    Please import your Google Contacts!
  </h2>
  <h2>
    <%= form_tag(google_authenticate_path, method: "get") do %>
    <%= label_tag(:q, "Page Size:") %>
    <%= number_field(:product, :price, in: 1.0..1000.0, step: 1) %>
    <%= submit_tag("Enter") %>
  <% end %>
  </h2>
</div>

Importam/app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :user_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :user_email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Importam/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

Importam/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

Importam/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

Importam/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>